/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendedorRouteImport } from './routes/vendedor'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as SolicitacoesRouteImport } from './routes/solicitacoes'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as MeusAceitesRouteImport } from './routes/meus-aceites'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ComercialRouteImport } from './routes/comercial'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicRefVisitaRouteImport } from './routes/api/public/ref-visita'
import { Route as ApiPublicHooksLembretesVencimentoRouteImport } from './routes/api/public/hooks/lembretes-vencimento'
import { Route as ApiPublicHooksAsaasSyncQueueRouteImport } from './routes/api/public/hooks/asaas-sync-queue'

const VendedorRoute = VendedorRouteImport.update({
  id: '/vendedor',
  path: '/vendedor',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitacoesRoute = SolicitacoesRouteImport.update({
  id: '/solicitacoes',
  path: '/solicitacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusAceitesRoute = MeusAceitesRouteImport.update({
  id: '/meus-aceites',
  path: '/meus-aceites',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialRoute = ComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRefVisitaRoute = ApiPublicRefVisitaRouteImport.update({
  id: '/api/public/ref-visita',
  path: '/api/public/ref-visita',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksLembretesVencimentoRoute =
  ApiPublicHooksLembretesVencimentoRouteImport.update({
    id: '/api/public/hooks/lembretes-vencimento',
    path: '/api/public/hooks/lembretes-vencimento',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAsaasSyncQueueRoute =
  ApiPublicHooksAsaasSyncQueueRouteImport.update({
    id: '/api/public/hooks/asaas-sync-queue',
    path: '/api/public/hooks/asaas-sync-queue',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRoute
  '/cliente': typeof ClienteRoute
  '/comercial': typeof ComercialRoute
  '/login': typeof LoginRoute
  '/meus-aceites': typeof MeusAceitesRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solicitacoes': typeof SolicitacoesRoute
  '/tarefas': typeof TarefasRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/vendedor': typeof VendedorRoute
  '/api/public/ref-visita': typeof ApiPublicRefVisitaRoute
  '/api/public/hooks/asaas-sync-queue': typeof ApiPublicHooksAsaasSyncQueueRoute
  '/api/public/hooks/lembretes-vencimento': typeof ApiPublicHooksLembretesVencimentoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRoute
  '/cliente': typeof ClienteRoute
  '/comercial': typeof ComercialRoute
  '/login': typeof LoginRoute
  '/meus-aceites': typeof MeusAceitesRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solicitacoes': typeof SolicitacoesRoute
  '/tarefas': typeof TarefasRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/vendedor': typeof VendedorRoute
  '/api/public/ref-visita': typeof ApiPublicRefVisitaRoute
  '/api/public/hooks/asaas-sync-queue': typeof ApiPublicHooksAsaasSyncQueueRoute
  '/api/public/hooks/lembretes-vencimento': typeof ApiPublicHooksLembretesVencimentoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRoute
  '/cliente': typeof ClienteRoute
  '/comercial': typeof ComercialRoute
  '/login': typeof LoginRoute
  '/meus-aceites': typeof MeusAceitesRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solicitacoes': typeof SolicitacoesRoute
  '/tarefas': typeof TarefasRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/vendedor': typeof VendedorRoute
  '/api/public/ref-visita': typeof ApiPublicRefVisitaRoute
  '/api/public/hooks/asaas-sync-queue': typeof ApiPublicHooksAsaasSyncQueueRoute
  '/api/public/hooks/lembretes-vencimento': typeof ApiPublicHooksLembretesVencimentoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/cliente'
    | '/comercial'
    | '/login'
    | '/meus-aceites'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/solicitacoes'
    | '/tarefas'
    | '/termos-de-uso'
    | '/vendedor'
    | '/api/public/ref-visita'
    | '/api/public/hooks/asaas-sync-queue'
    | '/api/public/hooks/lembretes-vencimento'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/cliente'
    | '/comercial'
    | '/login'
    | '/meus-aceites'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/solicitacoes'
    | '/tarefas'
    | '/termos-de-uso'
    | '/vendedor'
    | '/api/public/ref-visita'
    | '/api/public/hooks/asaas-sync-queue'
    | '/api/public/hooks/lembretes-vencimento'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cadastro'
    | '/cliente'
    | '/comercial'
    | '/login'
    | '/meus-aceites'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/solicitacoes'
    | '/tarefas'
    | '/termos-de-uso'
    | '/vendedor'
    | '/api/public/ref-visita'
    | '/api/public/hooks/asaas-sync-queue'
    | '/api/public/hooks/lembretes-vencimento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CadastroRoute: typeof CadastroRoute
  ClienteRoute: typeof ClienteRoute
  ComercialRoute: typeof ComercialRoute
  LoginRoute: typeof LoginRoute
  MeusAceitesRoute: typeof MeusAceitesRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolicitacoesRoute: typeof SolicitacoesRoute
  TarefasRoute: typeof TarefasRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  VendedorRoute: typeof VendedorRoute
  ApiPublicRefVisitaRoute: typeof ApiPublicRefVisitaRoute
  ApiPublicHooksAsaasSyncQueueRoute: typeof ApiPublicHooksAsaasSyncQueueRoute
  ApiPublicHooksLembretesVencimentoRoute: typeof ApiPublicHooksLembretesVencimentoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendedor': {
      id: '/vendedor'
      path: '/vendedor'
      fullPath: '/vendedor'
      preLoaderRoute: typeof VendedorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitacoes': {
      id: '/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/solicitacoes'
      preLoaderRoute: typeof SolicitacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-aceites': {
      id: '/meus-aceites'
      path: '/meus-aceites'
      fullPath: '/meus-aceites'
      preLoaderRoute: typeof MeusAceitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial': {
      id: '/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof ComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ref-visita': {
      id: '/api/public/ref-visita'
      path: '/api/public/ref-visita'
      fullPath: '/api/public/ref-visita'
      preLoaderRoute: typeof ApiPublicRefVisitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/lembretes-vencimento': {
      id: '/api/public/hooks/lembretes-vencimento'
      path: '/api/public/hooks/lembretes-vencimento'
      fullPath: '/api/public/hooks/lembretes-vencimento'
      preLoaderRoute: typeof ApiPublicHooksLembretesVencimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/asaas-sync-queue': {
      id: '/api/public/hooks/asaas-sync-queue'
      path: '/api/public/hooks/asaas-sync-queue'
      fullPath: '/api/public/hooks/asaas-sync-queue'
      preLoaderRoute: typeof ApiPublicHooksAsaasSyncQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CadastroRoute: CadastroRoute,
  ClienteRoute: ClienteRoute,
  ComercialRoute: ComercialRoute,
  LoginRoute: LoginRoute,
  MeusAceitesRoute: MeusAceitesRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolicitacoesRoute: SolicitacoesRoute,
  TarefasRoute: TarefasRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  VendedorRoute: VendedorRoute,
  ApiPublicRefVisitaRoute: ApiPublicRefVisitaRoute,
  ApiPublicHooksAsaasSyncQueueRoute: ApiPublicHooksAsaasSyncQueueRoute,
  ApiPublicHooksLembretesVencimentoRoute:
    ApiPublicHooksLembretesVencimentoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
